bump rev in docs

diff --git a/build/bump b/build/bump
--- a/build/bump
+++ b/build/bump
@@ -8,11 +8,14 @@ fi
 DIR=`dirname $0`
 cd $DIR/..
 
-CURRENT_REV=`build/current_rev`
+CURRENT_REV="$2"
+if [ -z "$CURRENT_REV" ] ; then
+  CURRENT_REV=`build/current_rev`
 
-if [ "$CURRENT_REV" == "" ]
-then
-  echo "Couldn't get CURRENT_REV" && exit 1
+  if [ "$CURRENT_REV" == "" ]
+  then
+    echo "Couldn't get CURRENT_REV" && exit 1
+  fi
 fi
 
 git grep -lF $CURRENT_REV | grep -v search_index.json | grep -v CHANGELOG.md | xargs perl -i -npe "s|$CURRENT_REV|$1|g"
